AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Buildkite On-Demand Agents

Transform: Buildkite-Agents-2020-03-09

Parameters:
  BuildkiteAgentTokenParameterPath:
    Type: AWS::SSM::Parameter::Name
    Description: An AWS SSM Parameter path where the buildkite agent token is stored. Defaults to /buildkite/agent-token
    Default: /buildkite/agent-token
  BuildkiteAgentImage:
    Type: String
    Default: keithduncan/buildkite-sidecar

Resources:
  Default:
    Type: Buildkite::ECS::TaskDefinition
    Properties:
      Image: keithduncan/buildkite-base
      BuildkiteAgentImage: !Ref BuildkiteAgentImage
      TaskFamily: buildkite

  Rails:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: agent
          EntryPoint:
            - /buildkite/bin/buildkite-agent
          Command:
            - start
          Essential: true
          Image: ruby:2.7
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: /aws/ecs/rails
              awslogs-stream-prefix: ecs
          Environment:
            - Name: BUILDKITE_BUILD_PATH
              Value: /workspace
            - Name: BUILDKITE_HOOKS_PATH
              Value: /buildkite/hooks
            - Name: BUILDKITE_PLUGINS_PATH
              Value: /buildkite/plugins
          Secrets:
            - Name: BUILDKITE_AGENT_TOKEN
              ValueFrom: !Ref BuildkiteAgentTokenParameterPath
          DependsOn:
            - ContainerName: agent-init
              Condition: SUCCESS
          VolumesFrom:
            - SourceContainer: agent-init
        - Name: agent-init
          EntryPoint:
            - /bin/sh
            - -c
          Command:
            - echo container=agent-init at=initalised
          Essential: false
          Image: !Ref BuildkiteAgentImage
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: /aws/ecs/rails
              awslogs-stream-prefix: ecs
      Cpu: 4096
      Memory: 8192
      Family: rails
      NetworkMode: awsvpc
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      RequiresCompatibilities:
        - FARGATE
  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [ecs-tasks.amazonaws.com]
          Action: ['sts:AssumeRole']
      Path: /BuildkiteAgentExecution/
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: FetchDecryptSecrets
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - 'ssm:GetParameter'
                  - 'ssm:GetParameters'
                Resource:
                  - !Sub
                      - 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${AgentToken}'
                      - AgentToken: !Ref BuildkiteAgentTokenParameterPath
              - Effect: Allow
                Action: kms:Decrypt
                Resource: !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/aws/ssm
  RailsLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: Rails
    Properties:
      LogGroupName: /aws/ecs/rails
      RetentionInDays: 1
